name: Deploy ShipIt
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SHIPIT_HOST }}
          username: shipit
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/shipit
            bash deploy/self-deploy.sh
